# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, MacOS-latest]
        go: [1.22]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: |
        make build ARCH=amd64

    - name: Test
      run: |
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          echo "Skip gofmt check on windows"
        else
          gofmt -d */*.go
        fi
      shell: bash
